package com.bank.account.model;

import com.bank.account.model.enums.AccountType;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * Represents a bank account entity stored in MongoDB.
 * Supports savings, checking, and fixed-term account types
 * with specific business rules per type and customer profile.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "accounts")
public class Account {

    /** Unique identifier generated by MongoDB. */
    @Id
    private String id;

    /** Unique account number assigned at creation. */
    @Indexed(unique = true)
    private String accountNumber;

    /** Type of bank account. */
    private AccountType accountType;

    /** ID of the primary owner of the account (from ms-customer). */
    private String customerId;

    /** Current available balance in the account. */
    @Builder.Default
    private BigDecimal balance = BigDecimal.ZERO;

    /**
     * Minimum opening amount required to create the account.
     * Can be zero for standard accounts.
     */
    @Builder.Default
    private BigDecimal minimumOpeningAmount = BigDecimal.ZERO;

    /**
     * Monthly maintenance fee applied to checking accounts.
     * Zero for savings and fixed-term accounts.
     */
    @Builder.Default
    private BigDecimal maintenanceFee = BigDecimal.ZERO;

    /**
     * Maximum number of free transactions per month.
     * Applies to savings accounts. Zero means unlimited.
     */
    @Builder.Default
    private Integer transactionLimit = 0;

    /**
     * Number of transactions already performed this month.
     * Resets at the start of each month.
     */
    @Builder.Default
    private Integer monthlyTransactionCount = 0;

    /**
     * Specific day of the month when a transaction is allowed.
     * Only applies to FIXED_TERM accounts.
     */
    private Integer transactionDayOfMonth;

    /**
     * List of customer IDs who are account holders.
     * Applies to business accounts (can have multiple holders).
     */
    @Builder.Default
    private List<String> holderIds = new ArrayList<>();

    /**
     * List of customer IDs who are authorized signers.
     * Applies to business accounts (can have zero or more).
     */
    @Builder.Default
    private List<String> authorizedSignerIds = new ArrayList<>();

    /** Indicates if the account is currently active. */
    @Builder.Default
    private Boolean status = true;

    /** Timestamp when the account was created. */
    @CreatedDate
    private LocalDateTime createdAt;

    /** Timestamp when the account was last updated. */
    @LastModifiedDate
    private LocalDateTime updatedAt;
}